# Generated by Django 5.0.2 on 2024-03-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_setting_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
