# Generated by Django 5.0.2 on 2024-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subject_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
