# Generated by Django 5.0.2 on 2024-03-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_contactus_subject_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media/product/'),
            preserve_default=False,
        ),
    ]
