# Generated by Django 5.0.2 on 2024-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
