# Generated by Django 5.0.4 on 2024-05-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
