# Generated by Django 5.0.2 on 2024-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('customer', 'Customer'), ('user', 'User'), ('menejer', 'Menejer')], default='customer', max_length=100, null=True),
        ),
    ]
